server:
  port: 8040
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Terry2001/SpringBootDemo.git/     # 配置git仓库的地址
          search-paths: configRepo                                  # git仓库地址下的相对地址，可以配置多个，用,分割。